### ISSUE TITLE
ZonedDateTime use in DataFrame join

### ISSUE THREAD

**Issue by omus** [JuliaTime/TimeZones.jl#103]
I was joining some DataFrames and noticed an issue which I'm uncertain what the best solution is:
```julia
julia> using TimeZones, DataFrames

julia> zdt_utc = ZonedDateTime(2017, 12, 1, 6, tz"UTC")
2017-12-01T06:00:00+00:00

julia> zdt_wpg = ZonedDateTime(2017, 12, 1, tz"America/Winnipeg")
2017-12-01T00:00:00-06:00

julia> zdt_utc == zdt_wpg  # ZonedDateTime are equal if their UTC representations are the same
true

julia> hash(zdt_utc) == hash(zdt_wpg)  # Hash differently because they use different time zones
false

julia> df1 = DataFrame(:time => zdt_utc, :value => 1)
1×2 DataFrames.DataFrame
│ Row │ time                      │ value │
├─────┼───────────────────────────┼───────┤
│ 1   │ 2017-12-01T06:00:00+00:00 │ 1     │

julia> df2 = DataFrame(:time => zdt_wpg, :value => 2)
1×2 DataFrames.DataFrame
│ Row │ time                      │ value │
├─────┼───────────────────────────┼───────┤
│ 1   │ 2017-12-01T00:00:00-06:00 │ 2     │

julia> df3 = DataFrame(:time => astimezone(zdt_wpg, tz"UTC"), :value => 3)
1×2 DataFrames.DataFrame
│ Row │ time                      │ value │
├─────┼───────────────────────────┼───────┤
│ 1   │ 2017-12-01T06:00:00+00:00 │ 3     │

julia> join(df1, df2, on=[:time], kind = :left)  # joining fails as `hash` is used to compare keys
1×3 DataFrames.DataFrame
│ Row │ time                      │ value │ value_1 │
├─────┼───────────────────────────┼───────┼─────────┤
│ 1   │ 2017-12-01T06:00:00+00:00 │ 1     │ missing │

julia> join(df1, df3, on=[:time], kind = :left)
1×3 DataFrames.DataFrame
│ Row │ time                      │ value │ value_1 │
├─────┼───────────────────────────┼───────┼─────────┤
│ 1   │ 2017-12-01T06:00:00+00:00 │ 1     │ 3       │
```
Possible solutions:
1. Make `(hash(zdt_utc) == hash(zdt_wpg)) == true`
2. Make DataFrames use `==` when performing a `join`
3. Allow giving DataFrames a custom hash function for columns (?)
4. Make the user convert the time zones to be the same

**Comment by omus** [comment]
Note that changing `(hash(zdt_utc) == hash(zdt_wpg)) == true` would also mean that `isequal(zdt_utc, zdt_wpg) == true`. This isn't ideal as right now `==` for `ZonedDateTime` means "the moments in time are equal" while `isequal` is used to refer to "these are identical" (time and time zone).

**Comment by omus** [comment]
Interestingly it was pointed out to me by Shashi that IndexTables use `cmp` when performing joins which means this works as I would have expected: http://juliadb.org/latest/api/joins.html#Joins-1

**Comment by omus** [comment]
I think solution 4 isn't ideal (what we have now) as this involves manual intervention and doesn't support a `DataFrame` where you want to keep `ZonedDateTime`s with heterogenous time zones.

**Comment by omus** [comment]
One, very out there, solution would be to have the concept of `isequal` be separated from `hash(x) == hash(y)` which would allow us to have hashing and `==` be logically equivalent and still support a "these are identical" operation in `isequal`. I don't think this is feasible due the amount of fallout this would case.

**Comment by strickek** [comment]
ZonedDateTime include at least 2 informations: The 'absolute' time in UTC and the information about TimeZone. I am not sure that the utc == utc criteria fits in any case, so an explizit decision to convert (4) may be not so bad.

**Comment by omus** [comment]
Looks like the solution we're going with will be number 1: `(hash(zdt_utc) == hash(zdt_wpg)) == true`. The reason for this choice comes how Julia does value-based hashing. For example:

```julia
julia> hash([1, 2]) == hash(1:2)
true

julia> hash(3.0) == hash(3)
true
```
Even though these use different types they end up hashing to the same value because they represent the same data. For `ZonedDateTime` the underlying representation is the UTC instant on the time line in which the associated time zone isn't relevant.

One unfortunate part about this change is that there isn't an equality function/operator which allows one to check that the UTC instant AND the time zone is equivalent. However, there may be a way to get `ZonedDateTime` to be an immutable bits type which would then allow us to perform this check with `===`.

See: https://github.com/JuliaTime/TimeZones.jl/pull/147
