### ISSUE TITLE
TimeZone parses z "-00:30" wrong

### ISSUE THREAD

**Issue by strickek** [JuliaTime/TimeZones.jl#132]
`parse(ZonedDateTime, "2017-11-14 11:03:53 -00:30", dateformat"yyyy-mm-dd HH:MM:SS z")`
2017-11-14T11:03:53+00:30

the same with

`ZonedDateTime("2017-11-14 11:03:53 -00:30", dateformat"yyyy-mm-dd HH:MM:SS z")`
2017-11-14T11:03:53+00:30

**Comment by omus** [comment]
Addressed in the TimeZones 0.6.4 release.
