### ISSUE TITLE
Type-piracy breaks Pkg

### ISSUE THREAD

**Issue by KristofferC** [JuliaTime/TimeZones.jl#179]
Loading this package breaks Pkg, see https://github.com/JuliaLang/Pkg.jl/issues/820#issuecomment-456403272

**Comment by omus** [comment]
More accurately extending Dates formatting changes the behaviour if you use `Z` or `z` in your date format before or after you load TimeZones. I've fixed the Pkg problem (https://github.com/JuliaLang/Pkg.jl/pull/1004) but in general we should rework the dates parsing/formatting to more gracefully allow for extension.

**Comment by KristofferC** [comment]
https://github.com/JuliaLang/Pkg.jl/pull/1004
