### ISSUE TITLE
Argument error when parsing UTC time 

### ISSUE THREAD

**Issue by jbendes** [JuliaTime/TimeZones.jl#183]
I am trying to run a `parse` on a UTC time:
```
parse(ZonedDateTime, "2019-01-19 20:16:20.796+00", dateformat"y-m-d HH:MM:SS.sssz")
```
and I am getting an error:
```
ArgumentError("Unable to parse date time. Expected directive Delim(\\z) at char 24")
```
Any ideas on how to fix it? This issue was originally discovered in https://github.com/invenia/LibPQ.jl/issues/59

**Comment by Nosferican** [comment]
Resolved?

**Comment by omus** [comment]
I'll close this as additional information is required.
