### ISSUE TITLE
Support using geolocation (longitude/latitude) to construct timezone

### ISSUE THREAD

**Issue by xue35** [JuliaTime/TimeZones.jl#197]
Some possible sample code below.

```julia
julia> using Pkg; Pkg.add("TimeZones"); using Timezones;
julia> tz"9.737196,52.368544"
Europe/Berlin (UMT+1)

julia> localtime("2019-03-11T02:19:48Z", tz"9.737196,52.368544")
2019-03-11T09:19:48
```

**Comment by omus** [comment]
The TimeZones.jl package currently relies on the data included in the [IANA time zone database](https://www.iana.org/time-zones). The database does not contain any geolocation mapping to time zones.

From a brief search you could get this functionality by implementing a Julia interface for  https://github.com/evansiroky/timezone-boundary-builder. However, I think such an interface would probably be best as a separate Julia package.

**Comment by xue35** [comment]
Thank you Curtis!Oy are right. I will explore a bit to create a new project based on the Geodb to get Timezone.

On Apr 25, 2019, at 10:32, Curtis Vogt <notifications@github.com> wrote:

The TimeZones.jl package currently relies on the data included in the IANA time zone database. The database does not contain any geolocation mapping to time zones.

From a brief search you could get this functionality by implementing a Julia interface for https://github.com/evansiroky/timezone-boundary-builder. However, I think such an interface would probably be best as a separate Julia package.

**Comment by omus** [comment]
> Has there been any development with getting a `TimeZones.TimeZone` from a set of longitude and latitude data?

Not as far as I know. I believe this functionality makes sense to exist in a separate Julia package based upon the prior conversation.
