### ISSUE TITLE
Add time zone extractor

### ISSUE THREAD

**Issue by CameronBieganek** [JuliaTime/TimeZones.jl#198]
Currently the only way to extract the time zone of a `ZonedDateTime` is by direct field access:

```
julia> tz = TimeZone("America/Chicago")
America/Chicago (UTC-6/UTC-5)

julia> x = ZonedDateTime(2017, 7, 15, 14, 5, TimeZone("America/Chicago"))
2017-07-15T14:05:00-05:00

julia> x.timezone
America/Chicago (UTC-6/UTC-5)

julia> x.timezone == tz
true
```

Interfaces that use direct field access are generally discouraged in Julia, so it would be nice if we had a time zone extractor like `tz()` or `timezone()`.

**Comment by omus** [comment]
There is already an accessor that does this called `timezone`. At the moment the function isn't exported so if you want to use it you need to do `using TimeZones: timezone` or `TimeZones.timezone()`.

I'll be sure to export it for the next release though as there really isn't a reason anymore to not export it.
