### ISSUE TITLE
ZonedTime?

### ISSUE THREAD

**Issue by galenlynch** [JuliaTime/TimeZones.jl#200]
Are there any plans to extend `ZonedDateTime` to a time zone aware [`Time`](https://docs.julialang.org/en/v1/stdlib/Dates/#Dates.Time), which wraps nanoseconds instead of milliseconds?

**Comment by galenlynch** [comment]
After thinking about this more, I'm not sure that such a type would be useful.

**Comment by omus** [comment]
I'll note there are some plans to possibly include a `ZonedDate` as has some uses (see docstring for [`today(::TimeZone)`](https://github.com/JuliaTime/TimeZones.jl/blob/33879acfdff141cf5c749a7bdf45acea449ffbe5/src/conversions.jl#L25-L40)). I'm not sure the same is true for just time however as you really need date to determine the offset in a time zone.

**Comment by galenlynch** [comment]
I'll just describe my use case and why I briefly thought it would be nice.

I want to represent timestamps coming from PostgreSQL, which have microsecond resolution. For my use case, the microseconds matter. I had been previously ignoring the time zone information, and made my own `PreciseDateTime`, which was just

```julia
struct PreciseDateTime
    datepart::Date
    timepart::Time
end
```

This gives me nanosecond resolution, and it's fairly easy to extend functionality from `Dates` to work with this new type (e.g. adding an interval).

Now I want to make this type aware of time zones. I guess a `ZonedDate` type would work, if it were to exist. What I ended up going with was instead:

```julia
struct PreciseDateTime
    zdt::ZonedDateTime
    nanos::Nanosecond
end
```

**Comment by galenlynch** [comment]
Alternatively, it would be great if `ZonedDateTime` itself wrapped nanoseconds, microseconds, or however fine resolution you can afford with something like an `Int128` underneath it all. Milliseconds are pretty coarse for a lot of scientific use cases.

**Comment by omus** [comment]
What may end up happening is having a parametric type which allows you to apply time zone information to any type of time instant: e.g. `Localized{DateTime}`. You can also use `Dates.UTInstant{...}` to get the resolution you're interested in which is [how `DateTime` already works](https://github.com/JuliaLang/julia/blob/3efdda65d4046a4825353dddc090a6235764fa8f/stdlib/Dates/src/types.jl#L106).

**Comment by galenlynch** [comment]
Yes but `DateTime` is fixed to having millisecond resolution, from what I can tell.
