### ISSUE TITLE
ERROR: ArgumentError: Unknown time zone "America/Denver"

### ISSUE THREAD

**Issue by 3ch01c** [JuliaTime/TimeZones.jl#206]
I suspect the problem is my proxy variables are being ignored. It looks like [`Base.download` is used to download the `tzdata` file](https://github.com/JuliaTime/TimeZones.jl/blob/b5e59679e7ff26e1682cc65417cfa5ea27c1ed46/src/tzdata/download.jl#L89), but [`Base.download` doesn't support proxies](https://github.com/JuliaLang/julia/issues/27043). It also looks like [HTTP.jl](https://github.com/JuliaWeb/HTTP.jl) could be an alternative to resolve this issue.

**Comment by omus** [comment]
Thanks for filing an issue. The package currently uses `Base.download` to avoid extra dependencies. Are you just trying to use the TimeZones package on your local machine or do you need to setup an automated installation?

**Comment by 3ch01c** [comment]
Sorry for the delayed response. It's for an automated installation that needs to be done offline. Something resolved the issue and I haven't been able to figure out what, so if I can reproduce the issue again, I'll reopen this.
