### ISSUE TITLE
TZ environment variable format

### ISSUE THREAD

**Issue by chrisoei** [JuliaTime/TimeZones.jl#210]
```
julia> using TimeZones

julia> mytz = "America/Los_Angeles"
"America/Los_Angeles"

julia> istimezone(mytz)
true

julia> ENV["TZ"] = mytz
"America/Los_Angeles"

julia> localzone()
ERROR: ArgumentError: Unhandled TZ environment variable format: "America/Los_Angeles"
```
Setting TZ to ":America/Los_Angeles" works, but most Linux systems I've seen don't use the colon in front.

**Comment by omus** [comment]
Thanks for the bug report. This can be easily added but I'd like to find a reference where this is documented. The [`tzset` man page](http://man7.org/linux/man-pages/man3/tzset.3.html) doesn't list that as a valid format.

**Comment by chrisoei** [comment]
If you run tzselect on Ubuntu 18.04 and choose the United States Pacific time zone, it shows:

```You can make this change permanent for yourself by appending the line
	TZ='America/Los_Angeles'; export TZ
to the file '.profile' in your home directory; then log out and log in again.
```
I think this is the TZ environment variable format Ubuntu uses during the installation procedure.

Similarly, Ubuntu's bash accepts this format:
$ echo $TZ
America/Los_Angeles
$ date
Fri Aug 23 13:24:17 PDT 2019
$ export TZ="America/New_York"
$ date
Fri Aug 23 16:24:28 EDT 2019

It's possible this format is outdated but still widely in use.

Also, some tutorials like
https://www.cyberciti.biz/faq/linux-unix-set-tz-environment-variable/
https://www.thegeekstuff.com/2010/09/change-timezone-in-linux/
https://www.vertica.com/docs/9.2.x/HTML/Content/Authoring/InstallationGuide/BeforeYouInstall/TZenvironmentVar.htm
mention this format for the TZ environment variable.

**Comment by omus** [comment]
I was hoping to find a reference to this format in a TZ specification document. I agree though that this is used commonly enough that it's worth adding.
