### ISSUE TITLE
Changes in printing on 1.3 causes tests to fail

### ISSUE THREAD

**Issue by KristofferC** [JuliaTime/TimeZones.jl#216]
Tests fail on upcoming 1.3 with

```
TimeZones: Test Failed at /root/.julia/packages/TimeZones/UXytc/test/utcoffset.jl:51
  Expression: sprint(show, UTCOffset(0, 0)) == "UTCOffset(Second(0), Second(0))"
   Evaluated: "UTCOffset(0 seconds, 0 seconds)" == "UTCOffset(Second(0), Second(0))"
```

Make some noise if this is a bad thing :)

**Comment by omus** [comment]
Thanks. I didn't expect this to get reverted in 1.3 but since it was already reverted as part of 1.3-rc1 and 1.3-rc2. As long as it doesn't get reverted in `master` and it finally makes it into 1.4 I'm happy.

https://github.com/JuliaLang/julia/pull/33178
