### ISSUE TITLE
ZonedDateTime(0)

### ISSUE THREAD

**Issue by scls19fr** [JuliaTime/TimeZones.jl#229]
Hello,

I have a code which use `DateTime(0)` for initialisation of a variable.
I need to change my code to use `ZonedDateTime` but `ZonedDateTime(0)` is not implemented.

This should probably be defined as a DateTime(0) with timezone UTC.

What is your opinion?

Kind regards

**Comment by scls19fr** [comment]
Maybe something like

```julia
ZonedDateTime(n::Int) = ZonedDateTime(DateTime(n), tz"UTC")
```

**Comment by scls19fr** [comment]
Sorry I didn't noticed `ZonedDateTime(0, tz"UTC")` is possible

**Comment by scls19fr** [comment]
But maybe implementing

```julia
ZonedDateTime(n::Int) = ZonedDateTime(n, tz"UTC")
```

should be considered.

**Comment by omus** [comment]
I'm not sure how often this situation comes up. If we add `ZonedDateTime(0)` I expect that we would also have to add support for `ZonedDateTime(0, 0, 0)` etc.

You're probably using `ZonedDateTime(0, tz"UTC")` as a sentinel value? You could probably just set a constant in your code/package to clean things up.

**Comment by scls19fr** [comment]
let's go for this solution
