### ISSUE TITLE
Convert between DateTime and ZonedDateTime

### ISSUE THREAD

**Issue by jebej** [JuliaTime/TimeZones.jl#25]
Hello, and thanks for the nice package. I have two questions:

1. The main page mentions string parsing of ZonedDateTime using DateFormat, but I can't see how to do that in the documentation (or in the code). Right now I am first parsing a string in a DateTime, and then feeding that in a ZoneDateTime.

2. Is it possible to convert a ZonedDateTime to a DateTime by stripping the timezone information out? I would like to plot some data as a function of time, and gadfly does not support ZonedDateTime. I also do not want to simply extract the UTC DateTime object, since I want the time in my local time zone...

Thanks

**Comment by omus** [comment]
Hi @jebej, 

> The main page mentions string parsing of ZonedDateTime using DateFormat, but I can't see how to do that in the documentation (or in the code). Right now I am first parsing a string in a DateTime, and then feeding that in a ZoneDateTime.

I just added yesterday documentation for dealing with parsing and formating `ZonedDateTime` instances. You can find the documentation under ["Conversion" in the development version](http://timezonesjl.readthedocs.io/en/latest/conversions/) of the documentation. Let me know if you have any feedback as you may be the first person, besides myself, to read it.

> Is it possible to convert a ZonedDateTime to a DateTime by stripping the timezone information out? I would like to plot some data as a function of time, and gadfly does not support ZonedDateTime. I also do not want to simply extract the UTC DateTime object, since I want the time in my local time zone...

Yes, it is totally possible to convert a `ZonedDateTime` to a `DateTime`. There are two functions that aren't currently exported but are safe to use:

```julia
julia> using TimeZones

julia> zdt = now(localzone())
2016-05-27T22:05:40.065-05:00

julia> TimeZones.utc(zdt)  # DateTime in UTC
2016-05-28T03:05:40.065

julia> TimeZones.localtime(zdt)  # DateTime in localtime
2016-05-27T22:05:40.065
```
I'm currently not happy with the names of these functions so they may change in the future. Once I decide on a good name I'll be sure to export these functions and mention them in the documentation.

Thanks for mentioning that `ZonedDateTime`s aren't supported in Gadfly. I'll add that to my personal TODO list but I'm more than happy if you want to make a PR.

**Comment by jebej** [comment]
Thanks for the prompt answer. The documentation is good. It might be worth it to add an example showing the DateFormat when parsing with a timezone like "America/Toronto", because it is unclear how many Zs are needed (I discovered 1 was sufficient).

It seems that it is currently much faster to parse a time string in a DateTime object first and then passing that to a ZonedDateTime:

Here are some timings parsing directly in a ZonedDateTime
```
  4.477657 seconds (17.23 M allocations: 695.524 MB, 4.24% gc time)
  3.822712 seconds (16.62 M allocations: 670.075 MB, 3.56% gc time)
  3.886814 seconds (16.62 M allocations: 670.189 MB, 5.83% gc time)
```
and parsing into a DateTime followed by attaching the timezone:
```
  0.823652 seconds (618.68 k allocations: 24.445 MB, 1.32% gc time)
  0.234971 seconds (229.85 k allocations: 8.429 MB)
  0.247586 seconds (229.85 k allocations: 8.429 MB)
```

**Comment by omus** [comment]
I'll update the documentation to mention how the number of slot characters work.

Interesting. The parsing code for a `ZonedDateTime` is just an extension on the `DateTime` parsing code. Could you provide an example of the code you are using for your timings?

**Comment by jebej** [comment]
Going through DateTime first:
```julia
df = Dates.DateFormat("yyyymmddHH:MM:SS")
ltz = localzone()
# Loop through Dict array
for vv in v["temps"]
            Time[i] = ZonedDateTime(DateTime("$(daystr)$(vv["Time"])",df),ltz)
end
```
and parsing directly into a ZonedDateTime
```julia
df = Dates.DateFormat("yyyymmddHH:MM:SSZ")
# Loop through Dict array
for vv in v["temps"]
            Time[i] = ZonedDateTime("$(daystr)$(vv["Time"])America/Toronto",df)
end
```

**Comment by omus** [comment]
Thanks. I haven't had time to dig into it but I expect the performance issue is from instantiating a TimeZone on each iteration of the loop.

**Comment by jebej** [comment]
That may very well be the case. In fact the line 'ltz = localtimezone()' takes almost half the total time in the first example.

**Comment by omus** [comment]
Also worth noting that `localzone` is rather slow to instantiating the time zone versus `TimeZone`:

```julia
julia> @time localzone();
  0.016640 seconds (12.28 k allocations: 700.016 KB)
America/Toronto (UTC-5/UTC-4)

julia> @time TimeZone("America/Toronto");
  0.003179 seconds (12.15 k allocations: 502.359 KB)
America/Toronto (UTC-5/UTC-4)
```

**Comment by omus** [comment]
I finally had some time to investigate this issue and I believe I've solved the issue. Here is the test I was using:
```julia
using TimeZones

function test1(n=1000)
    df = Dates.DateFormat("yyyymmddHH:MM:SS")
    ltz = TimeZone("America/Toronto")
    arr = Array{ZonedDateTime}(n)
    for (i, s) in enumerate(repeated("2016060701:02:03", n))
        arr[i] = ZonedDateTime(DateTime(s,df),ltz)
    end
    return arr
end

function test2(n=1000)
    df = Dates.DateFormat("yyyymmddHH:MM:SS ZZZ")
    arr = Array{ZonedDateTime}(n)
    for (i, s) in enumerate(repeated("2016060701:02:03 America/Toronto", n))
        arr[i] = ZonedDateTime(s,df)
    end
    return arr
end
```

Results pre-optimization:
```julia
julia> @time test1();  # compiling
  1.426188 seconds (2.21 M allocations: 96.756 MB, 1.36% gc time)

julia> @time test2();  # compiling
  2.948299 seconds (12.74 M allocations: 516.867 MB, 3.43% gc time)

julia> @time test1();
  0.030262 seconds (112.31 k allocations: 3.636 MB, 15.71% gc time)

julia> @time test2();
  2.647921 seconds (12.27 M allocations: 494.236 MB, 3.82% gc time)
```

Results post-optimization:
```julia
julia> @time test1();  # compiling
  1.516624 seconds (2.27 M allocations: 100.308 MB, 1.31% gc time)

julia> @time test2();  # compiling
  0.363229 seconds (546.80 k allocations: 23.914 MB, 1.22% gc time)

julia> @time test1();
  0.017654 seconds (100.16 k allocations: 3.146 MB)

julia> @time test2();
  0.020303 seconds (120.17 k allocations: 3.864 MB)
```
The core issue was that we were deserializing the TimeZone for every call. Now once a TimeZone is loaded into memory we keep a reference so we can load it faster the next time. An additional benefit of this is now: `TimeZone(x) === TimeZone(x)`

**Comment by omus** [comment]
@jebej I've improved parsing speed for TimeZones v0.2.0. Could you try out this version to ensure it helps for your use case?

**Comment by jebej** [comment]
Hey @omus, I'll try it as soon as I have some time (probably this weekend). Thanks for looking into this.

**Comment by jebej** [comment]
The problem is solved on my end as well. The test that took ~4sec now takes ~0.05 seconds. Thanks!

Regarding the conversion to DateTime, I do not mind the names, but it might be worth it having a function that converts a ZonedDateTime into a DateTime with an arbitrary timezone. Something like this:

```julia
julia> using TimeZones

julia> zdt = now(localzone())
2016-05-27T22:05:40.065-05:00

julia> TimeZones.DateTime(zdt,"America/Toronto")  # DateTime in arbitrary TimeZone
2016-05-27T22:05:40.065
```

**Comment by omus** [comment]
Glad things are solved. I'm going to close this issue as the original problem has been solved.

As for your suggestion: I definitely don't love the `localtime` and `utc` function names and do think these functions need to be revised in some way. Unfortunately I don't think your suggestion is the right solution either as I don't think users want to convert a `ZonedDateTime` into a local `DateTime` with a different time zone:

```julia
julia> using TimeZones

julia> zdt = now(TimeZone("Europe/Warsaw"))
2016-06-20T15:50:12.619+02:00

julia> TimeZones.DateTime(zdt, "America/Toronto")  
2016-06-20T09:50:12.619
```
I think what we're looking for is to be able to convert a `ZonedDateTime` to a `DateTime` by either dropping the timezone information (eg. localtime: `2016-06-20T15:50:12.619+02:00` → `2016-06-20T15:50:12.619`) or by getting a UTC `DateTime` (eg. utc: `2016-06-20T15:50:12.619+02:00` → `2016-06-20T13:50:12.619`)

**Comment by omus** [comment]
The conversion from a `ZonedDateTime` to `DateTime` is lossy and really shouldn't be done very often. Users can convert a `ZonedDateTime` into any `TimeZone` they want using `astimezone`.

I personally think it's dangerous to pass around `DateTime` without any `TimeZone` information especially if you are referring to an instant of time. To me a `DateTime` like `DateTime(2016,6,20,10)` is ambiguous and could represent 10AM in any time zone. If you do send a timestamp (typically referring to [Unix time](https://en.wikipedia.org/wiki/Unix_time)) to someone else the timestamp implicitly is a UTC representation.
