### ISSUE TITLE
Add 'Z' for Zulu time to deps/tzsource/utc

### ISSUE THREAD

**Issue by Nosferican** [JuliaTime/TimeZones.jl#250]
The discussion is whether a timestamp with timezone à la `2018-03-03T01:05:30Z` should be considered in the special cases. The idea is for `Z` to have as special terms `Z`/`Zulu` as special cases similar to the current ones (`UTC`/`GMT`). Use case is the GitHub API. Would be happy to make the PR if it seems like the right choice.

**Comment by omus** [comment]
I'll point out that `Z` already works for parsing but unfortunately it's expecting milliseconds to be included:
```julia
julia> parse(ZonedDateTime, "2018-03-03T01:05:30.000Z")
2018-03-03T01:05:30+00:00
```
You can get this to work by using a custom date format:
```julia
julia> using Dates, TimeZones

julia> parse(ZonedDateTime, "2018-03-03T01:05:30Z", dateformat"yyyy-mm-dd\THH:MM:SSz")
2018-03-03T01:05:30+00:00
```
