### ISSUE TITLE
Moving package to new GitHub Org

### ISSUE THREAD

**Issue by omus** [JuliaTime/TimeZones.jl#26]
TimeZones.jl has been busy and it made sense for it to reside in a GitHub organization rather than in a personal repo. Since none of the existing Julia organizations seemed to make sense to be the home for TimeZones.jl a new organization was created: JuliaTime

TODO
- [x] Create new GitHub organization [JuliaTime](https://github.com/JuliaTime)
- [x] Create new JuliaTime logo
- [x] Grant Appveyor access to JuliaTime org
- [x] Grant Travis CI access to JuliaTime org
- [x] Grant Codecov access to JuliaTime org
- [x] Grant Nightli.es access to JuliaTime org
- [x] Add JuliaTime to the julialang.org/community page ([PR](https://github.com/JuliaLang/julialang.github.com/pull/389))
- [x] Move package from quinnj/TimeZones.jl to JuliaTime/TimeZones.jl
- [x] Update URL references within repo (0b3a7fe)
- [x] Update TimeZones.jl URL in METADATA.jl ([PR](https://github.com/JuliaLang/METADATA.jl/pull/5391))
- [ ] Have TimeZones.jl added to IANA's [list of a "tz compilers"](https://www.iana.org/time-zones/repository/tz-link.html)
    - [x] [Contact IANA](http://mm.icann.org/pipermail/tz/2016-June/023813.html)
- [x] Update manual reference to TimeZones.jl ([PR](https://github.com/JuliaLang/julia/pull/16955))
- [x] Announce JuliaTime organization on [julia-dev](https://groups.google.com/forum/#!forum/julia-dev)
    - [x] Get posting privileges to julia-dev
    - [x] Post message (awaiting approval)

**Comment by jebej** [comment]
Nice logo :)

**Comment by omus** [comment]
Thanks :)

**Comment by omus** [comment]
I suspect that getting added to IANA's list of compilers will take a long time if it happens at all.
