### ISSUE TITLE
Windows timezone XML on unicode website seems dead

### ISSUE THREAD

**Issue by racinmat** [JuliaTime/TimeZones.jl#269]
Website http://unicode.org/repos/cldr/trunk/common/supplemental/windowsZones.xml on https://github.com/JuliaTime/TimeZones.jl/blob/master/src/winzone/WindowsTimeZoneIDs.jl#L9 does not return XML.

**Comment by omus** [comment]
Looks like I should switch to using the GitHub repo as the reference: https://raw.githubusercontent.com/unicode-org/cldr/master/common/supplemental/windowsZones.xml
