### ISSUE TITLE
Mocking dependency

### ISSUE THREAD

**Issue by tbreloff** [JuliaTime/TimeZones.jl#30]
Can you fill me in on the reason behind Mocking for this package?  I'm seeing:

```
INFO: Recompiling stale cache file /home/tom/.julia/lib/v0.5/CTechCommon.ji for module CTechCommon.
WARNING: eval from module Mocking to CTechCommon:    
Expr(:module, true, :##262, Expr(:block, Expr(:line, 108, :/home/tom/.julia/v0.5/Mocking/src/Mocking.jl)::Any, Expr(:line, 108, :/home/tom/.julia/v0.5/Mocking/src/Mocking.jl)::Any)::Any)::Any
  ** incremental compilation may be broken for this module **

WARNING: replacing module ##262
```

Is this something I have to deal with forever, or is it a temporary problem?

**Comment by omus** [comment]
The reason TimeZones.jl uses Mocking.jl is for testing the `localzone` function.

Due to the way Mocking.jl is implemented it dynamically creates modules on the fly but only when running `Pkg.test`. The warning you're seeing should be eliminated in the future but for now you can safely ignore it. I'll see if I can permanently solve the issue.

**Comment by tbreloff** [comment]
Thanks for the quick response. So you're saying it's an incorrect warning?  Will it negatively impact precompilation in any way?

**Comment by omus** [comment]
> `** incremental compilation may be broken for this module **`

The warning is vague enough that technically it is correct. 

> Will it negatively impact precompilation in any way?

No there won't be any negative impacts. Pre-compilation should work as if Mocking doesn't exist.

**Comment by omus** [comment]
@tbreloff I believe I just found a way to eliminate the warning.

**Comment by omus** [comment]
@tbreloff can you confirm that the issue has been resolved now that Mocking v0.2.1 is out?

**Comment by tbreloff** [comment]
Yes it seems to be resolved.  Thanks!

**Comment by lilinjn** [comment]
Can the Mocking dependency be moved to a REQUIRE file in the test folder?

**Comment by omus** [comment]
@lilinjn unfortunately it cannot be just in the test REQUIRE file as `@mock` needs to be present in the source. I may be able to make a placeholder macro to avoid having the dependency but that hasn't seemed necessary.

Are you having a problem with the Mocking.jl dependency?

**Comment by lilinjn** [comment]
Thanks for the clarification -- I am not having any concrete problems with Mocking;  I have a particularly slim application that only relies on JSON and TimeZones and was wondering if Mocking was being pulled in due to a simple mistake.
