### ISSUE TITLE
Drop support for Julia < 1.3

### ISSUE THREAD

**Issue by omus** [JuliaTime/TimeZones.jl#340]
As mentioned in https://github.com/JuliaTime/TimeZones.jl/pull/339#discussion_r629512977 it's becoming increasingly difficult to support Julia 1.0 (the current LTS). In order to keep LTS support but not be hamstrung by it we should probably drop support for Julia 1.0 in TimeZones 1.6 and just provide limited updates to TimeZones 1.5.

Limited support would include:
- Bug fixes
- Updates for new tzdata releases

**Comment by ViralBShah** [comment]
Julia version is now the new LTS in Project.toml
