### ISSUE TITLE
Package artifacts and distribute using our standard architecture

### ISSUE THREAD

**Issue by ViralBShah** [JuliaTime/TimeZones.jl#343]
I wonder if it would be more robust to have the artifacts packaged up as a JLL and distributed like other binary artifacts.

**Comment by omus** [comment]
The artifacts used by this package are just the tzdata archives provided by IANA. Currently TimeZones.jl extracts the tzsource files, compiles this information into the internal TimeZones.jl representation, and the serializes that information to disk during package build time. If we introduce a JLL I think it makes the most sense to store the serialized internal representation as the JLL artifact. Mainly the only thing holding up this work is picking a serialization method that works across Julia versions.

**Comment by KristofferC** [comment]
One thing that could be done is to do the compilation in `__init__` instead and use https://github.com/JuliaPackaging/Scratch.jl to store the resulting files (instead of storing them inside the package folder). That would make the package work with e.g. PackageCompiler.

**Comment by StefanKarpinski** [comment]
There's not really any reason for this to be a JLL, is there? It's not platform specific and doesn't require a fancy cross-compilation toolchain, it's just an artifact with a build step, right?

**Comment by ViralBShah** [comment]
I meant "bundle it in a standard way and distribute using our infrastructure, and make it more packagecompiler friendly".

**Comment by StefanKarpinski** [comment]
Might it be good enough to include a script that can be run when making a release that downloads the timezone files, processes them, bundles them up the way the package wants them, pushes that to GitHub along with the release and generates the corresponding `Artifacts.toml` file? That way the user can just download ready-to-use artifacts that are already in the right format?

**Comment by staticfloat** [comment]
Is the problem that the serialization format is Julia-version-specific?

**Comment by ViralBShah** [comment]
Yes: https://github.com/JuliaTime/TimeZones.jl/issues/343#issuecomment-848793417

**Comment by DilumAluthge** [comment]
Can it be serialized to e.g. JSON? And then we can use JSON3 and StructTypes to deserialize it directly back to Julia types?

**Comment by KristofferC** [comment]
Use Scratch space as a cache and serialize it during runtime to a folder based on the julia version?

**Comment by ViralBShah** [comment]
Seems like we should do that right away. I do wonder if different artifacts can be made for every Julia version.

**Comment by KristofferC** [comment]
You can just prefix the scratch folder with the julia version for example.

**Comment by omus** [comment]
As of PR #441 this package uses typically precomputed time zones artifacts via the TZJData.jl package. For users with advanced needs scratch spaces are also used for manual time zone compilation if required. Included in TimeZones release 1.12.
