### ISSUE TITLE
Tests failing on pkgeval

### ISSUE THREAD

**Issue by tkelman** [JuliaTime/TimeZones.jl#35]
I think there was a database update recently: http://pkg.julialang.org/detail/TimeZones.html

**Comment by omus** [comment]
The 2016g IANA database release reduced the total number of unique abbreviations which is causing the failure. I'll update test.

From the release notes (ftp://ftp.iana.org/tz/tzdb/NEWS):

> Several zones in Antarctica and the former Soviet Union, along
> with zones intended for ships at sea that cannot use POSIX TZ
> strings, now use numeric time zone abbreviations instead of
> invented or obsolete alphanumeric abbreviations.  The affected
> zones are Antarctica/Casey, Antarctica/Davis,
> Antarctica/DumontDUrville, Antarctica/Mawson, Antarctica/Rothera,
> Antarctica/Syowa, Antarctica/Troll, Antarctica/Vostok,
> Asia/Anadyr, Asia/Ashgabat, Asia/Baku, Asia/Bishkek, Asia/Chita,
> Asia/Dushanbe, Asia/Irkutsk, Asia/Kamchatka, Asia/Khandyga,
> Asia/Krasnoyarsk, Asia/Magadan, Asia/Omsk, Asia/Sakhalin,
> Asia/Samarkand, Asia/Srednekolymsk, Asia/Tashkent, Asia/Tbilisi,
> Asia/Ust-Nera, Asia/Vladivostok, Asia/Yakutsk, Asia/Yekaterinburg,
> Asia/Yerevan, Etc/GMT-14, Etc/GMT-13, Etc/GMT-12, Etc/GMT-11,
> Etc/GMT-10, Etc/GMT-9, Etc/GMT-8, Etc/GMT-7, Etc/GMT-6, Etc/GMT-5,
> Etc/GMT-4, Etc/GMT-3, Etc/GMT-2, Etc/GMT-1, Etc/GMT+1, Etc/GMT+2,
> Etc/GMT+3, Etc/GMT+4, Etc/GMT+5, Etc/GMT+6, Etc/GMT+7, Etc/GMT+8,
> Etc/GMT+9, Etc/GMT+10, Etc/GMT+11, Etc/GMT+12, Europe/Kaliningrad,
> Europe/Minsk, Europe/Samara, Europe/Volgograd, and
> Indian/Kerguelen.  For Europe/Moscow the invented abbreviation MSM
> was replaced by +05, whereas MSK and MSD were kept as they are not
> our invention and are widely used.
