### ISSUE TITLE
Should UNICODE_CLDR_VERSION be bumped?

### ISSUE THREAD

**Issue by LightAndLight** [JuliaTime/TimeZones.jl#350]
A new Unicode CLDR version (`release-38-1`) was added to Artefacts.toml in [this commit](https://github.com/JuliaTime/TimeZones.jl/commit/faa208e8a7c4f6f25b9b50668eacc03a4b3e0900) but `UNICODE_CLDR_VERSION` ([here](https://github.com/JuliaTime/TimeZones.jl/blob/master/src/winzone/WindowsTimeZoneIDs.jl#L10)) remains at `"release-37"`.

Should `UNICODE_CLDR_VERSION` be bumped?

**Comment by omus** [comment]
Yes it should be updated. I'll note `release-39` is out so we'll just jump to that.
