### ISSUE TITLE
Avoid loading TimeZones at build time

### ISSUE THREAD

**Issue by IanButterworth** [JuliaTime/TimeZones.jl#357]
It's unusual to load the package itself during build time 
https://github.com/JuliaTime/TimeZones.jl/blob/ae1e58383aae69b1571177871e2d6d375999fe1c/deps/build.jl#L1

This doesn't play well with the new pkg parallel precompilation as it forces TimeZones and all its dependencies to be precompiled in series (load-time precompilation) slowly during build time.
So while pkg is reporting `building TimeZones` it's probably actually spending a bunch of that time precompiling.

It may be a contributing factor in https://github.com/JuliaTime/TimeZones.jl/issues/331 given it might be causing some things to happen out of order?

**Comment by omus** [comment]
In PR #441 the `deps/build.jl` was removed so this is no longer an issue. Included in TimeZones release 1.12
