### ISSUE TITLE
io.slotparse, io.slotformat fail on v0.6-dev

### ISSUE THREAD

**Issue by JeffreySarnoff** [JuliaTime/TimeZones.jl#44]
ERROR: LoadError: LoadError: TypeError: Type{...} expression: expected UnionAll, got Type{Slot}
Stacktrace:
 [1] include_from_node1(::String) at ./loading.jl:539
 [2] include(::String) at ./sysimg.jl:14
 [3] include_from_node1(::String) at ./loading.jl:539
 [4] eval(::Module, ::Any) at ./boot.jl:235
 [5] require(::Symbol) at ./loading.jl:453
while loading /home/jas/.julia/v0.6/TimeZones/src/io.jl, in expression starting on line 61
while loading /home/jas/.julia/v0.6/TimeZones/src/TimeZones.jl, in expression starting on line 51

**Comment by omus** [comment]
Thanks for reporting the issue. As part of https://github.com/JuliaLang/julia/pull/19545 the internals of the DateTime parsing and formatting changed. I have some work to do before TimeZones.jl will be functional on 0.6 but I could push out a version without formatting and parsing in the mean time if need be.

**Comment by JeffreySarnoff** [comment]
If that would be much work and not move this forward for 0.6 then, don't. OTOH ... (I posted the issue after playing around with timestamp functions for v0.6).

**Comment by omus** [comment]
I've been actively working on this. Basically the hold up with Julia 0.6 is that the fast parsing code no longer supports extending DateFormat. I've made a [PR which addresses this in base Julia](https://github.com/JuliaLang/julia/pull/20952).

**Comment by JeffreySarnoff** [comment]
It looks like the i686 build just ran out of time and did not run into difficulty.

**Comment by omus** [comment]
TimeZones now works with the latest Julia nightly build.

**Comment by JeffreySarnoff** [comment]
I got the new nightly.
Version 0.6.0-pre.alpha.167 (2017-03-17 17:34 UTC) 
Commit 762b943 (0 days old master)
x86_64-pc-linux-gnu

did Pkg.rm("TimeZones") twice, then
Pkg.add("TimeZones")
# ...
WARNING: could not import Dates.slotparse into TimeZones
WARNING: could not import Dates.slotformat into TimeZones
ERROR: LoadError: LoadError: TypeError: Type{...} expression: expected UnionAll, got Type{Slot}
Stacktrace:
 [1] include_from_node1(::String) at ./loading.jl:539
 [2] include(::String) at ./sysimg.jl:14
 [3] include_from_node1(::String) at ./loading.jl:539
 [4] eval(::Module, ::Any) at ./boot.jl:235
 [5] require(::Symbol) at ./loading.jl:453
while loading /home/jas/.julia/v0.6/TimeZones/src/io.jl, in expression starting on line 60
while loading /home/jas/.julia/v0.6/TimeZones/src/TimeZones.jl, in expression starting on line 51

**Comment by omus** [comment]
[New tagged version](https://github.com/JuliaLang/METADATA.jl/pull/8378) isn't available yet. You should be able to get things working with `Pkg.checkout("TimeZones")`.

**Comment by JeffreySarnoff** [comment]
got it working now -- thank you for the attention and effort
