### ISSUE TITLE
Tests failing again

### ISSUE THREAD

**Issue by tkelman** [JuliaTime/TimeZones.jl#45]
`apia.transitions[3] == Transition(DateTime(1911,1,1,11,26,56),zone["WSST_OLD"])`

http://pkg.julialang.org/detail/TimeZones.html

about that pinning to a specific version...

**Comment by omus** [comment]
Thanks @tkelman. I'll fix this issue first and start working on the pinned tzdata changes.

**Comment by omus** [comment]
Fixed by 1bbc361bdda4ce54bed895fbacbbdbbae71428a4
