### ISSUE TITLE
Consider more restrictive compat with TZJData

### ISSUE THREAD

**Issue by green-nsk** [JuliaTime/TimeZones.jl#477]
Related to https://github.com/JuliaTime/TZJData.jl/issues/31

TZJData only releases "minor" versions on a new IANA tzdata release. I imagine it's worth at least doing a minor bump of TimeZones.jl for releases of TZJData. Not sure if Julia compat entries are expressive enough for that or not.

**Comment by omus** [comment]
I don't think having a compat entry for TZJData.jl in TimeZones.jl is a good idea as the current setup allows you to pick and choose which version of TZJData.jl you want to use with TimeZones.jl. This flexibility allows someone to keep using an old version of TZJData.jl but still get the latest features and bug fixes in TimeZones.jl.

I've added some alternative ideas in https://github.com/JuliaTime/TZJData.jl/issues/31
