### ISSUE TITLE
BUG: Using TimeZones breaks data import

### ISSUE THREAD

**Issue by clizbe** [JuliaTime/TimeZones.jl#481]
I am using Dates in a notebook and wanted to use TimeZones to adjust some data.
Since adding 'using TimeZones' to my Pluto notebook, I get this error when trying to read-in data.
It also makes the Pluto notebook work like crazy and eventually time-out.

The line was working fine before, and removing the 'using TimeZones' makes it work again.
I suspect it's some conflict with the Dates package in asserting data format?

![image](https://github.com/user-attachments/assets/e781e49d-db03-4d36-8784-45b370494bd2)

Julia 1.10.5
using Dates, DataFrames, CSV, XLSX, Plots, Statistics, StatsPlots, EasyFit, PlutoUI, TimeZones

Sorry can't give much more info right now!

**Comment by omus** [comment]
I suspect what may be going on is you are defining `dateformat"YYYY-MM-DDTHH:MM:SSZ"` before you are importing TimeZones. Doing that results in `Z` being interpreted as a literal character when TimeZones is not imported but the behavior changes after TimeZones is imported. You may want to try using `dateformat"YYYY-MM-DD\THH:MM:SS\Z"` and check if the problem goes away. 

If that isn't the problem then uploading you Manifest.toml and some steps to reproduce the problem would be helpful.

**Comment by clizbe** [comment]
Yes that worked, thank you!

**Comment by omus** [comment]
Related to: https://github.com/JuliaLang/julia/issues/29339
