### ISSUE TITLE
Decrease load on unicode.org

### ISSUE THREAD

**Issue by IlyaFinkelshteyn** [JuliaTime/TimeZones.jl#55]
Last couple of month we (AppVeyor.com) become blocked/throttled by unicode.org. We use single public IP, so this affects all users. We contacted unicode.org people and they told that this is because excessive use of their server from our public IP. Also they said that their source repository is not intended for access by production systems. I searched GitHub and came across [this commit](https://github.com/JuliaTime/TimeZones.jl/commit/8f4b227a168877a70430bdc47c40037ac617a133)

If you could default to cached XML and request repo directly more rarely (or from different machine) just to refresh the cache, this might help us.

**Comment by omus** [comment]
I can switch the default to use the cached version when running within a CI environment.

**Comment by IlyaFinkelshteyn** [comment]
Thanks a lot!

**Comment by tkelman** [comment]
Also shouldn't be downloading a separate unversioned copy on every user's machine every time they install, upgrade, or build the package; and never clean up the result. This is just another variant of the same repeatability concern with the tzdata itself.

**Comment by omus** [comment]
I'm working on some code to reduce network traffic, correct reproducibility, and allow users to have access to the latest data.

**Comment by tkelman** [comment]
Any update?

**Comment by omus** [comment]
Still working on this. I'm hoping to have the code ready by the end of the week.
