### ISSUE TITLE
v0.6 and abstract types

### ISSUE THREAD

**Issue by JeffreySarnoff** [JuliaTime/TimeZones.jl#56]
Do you prefer not to do `using Compat` and `@compat abstract type Typename end`?
There are only two places where the deprecation warning comes up in master.

WARNING: deprecated syntax "abstract TimeError<:Exception" at /home/jas/.julia/v0.6/TimeZones/src/types.jl:24.
Use "abstract type TimeError<:Exception end" instead.

WARNING: deprecated syntax "abstract Local<:TimeZone" at /home/jas/.julia/v0.6/TimeZones/src/interpret.jl:4.
Use "abstract type Local<:TimeZone end" instead.

**Comment by omus** [comment]
Thanks. I'll update those lines
