### ISSUE TITLE
Move tzdata download into an artifact

### ISSUE THREAD

**Issue by omus** [JuliaTime/TimeZones.jl#63]
See [discussion](https://github.com/JuliaTime/TimeZones.jl/pull/58#discussion_r109893372) for details.

**Comment by iamed2** [comment]
Whenever this happens, while you're doing that, could you add support for building the tzcode binaries of the same version? I'll need that for LibPQ.jl

**Comment by omus** [comment]
No plans currently do this but outside motivation is always helpful :)

**Comment by Nosferican** [comment]
This should be revisited now that we support artifacts.

**Comment by omus** [comment]
Some additional motivation for switching to use artifacts for this: https://github.com/invenia/Memento.jl/issues/161

**Comment by omus** [comment]
@iamed2 mentioned this to me:

> Python's now providing compiled tzdata as a package (maintained by the Python core devs): https://pypi.org/project/tzdata/
> It exists to support https://www.python.org/dev/peps/pep-0615/

**Comment by giordano** [comment]
I don't know the details of how this package fetches the tzdata, but my understanding is that it shouldn't be too hard to use an `Artifacts.toml` that you can update over time to add new versions as they are released.  The package can then download when requested.
