### ISSUE TITLE
Export TimeOffset

### ISSUE THREAD

**Issue by joshbode** [JuliaTime/TimeZones.jl#75]
It looks like `TimeZones.TZData.TimeOffset` is being used primarily as an internal helper type for parsing the timezone files, however it is quite a useful type in its own right - I'm using it to store times sourced from my own data.

```julia
julia> date = ZonedDateTime(now(), localzone())
julia> offset = TimeZones.TZData.TimeOffset("01:00")
julia> date + offset
2017-05-30T11:49:01.386+10:00
```

This type has moved/changed names a few times, which is fine for an internal type, but given its utility could this be elevated to an exported type?

Happy to make the PR if this is acceptable :)

**Comment by omus** [comment]
What are you using `TimeOffset` for? You may want to checkout [`Base.Dates.Time`](https://docs.julialang.org/en/latest/stdlib/dates.html#Base.Dates.Time-NTuple{5,Int64}). I originally was going to drop `TimeOffset` and switch over to `Time` but it needed a couple extra including string parsing, negative offsets, and offsets which exceed 24 hours.

**Comment by joshbode** [comment]
Ah - I didn't realise `Base.Dates.Time` existed - I'm still mostly using 0.5 where I don't believe it exists.

I started using `TimeOffset` in v0.2.5 when it was invitingly called `TimeZones.Time` and quite conveniently parsed times in some of the data I work with, which are provided in a separate column to the dates (parsed via `Date`), after which I literally add them together to get a `ZonedDateTime` (e.g. `ZonedDateTime(DateTime(date) + time, tz)`).

What I possibly should be doing is appending the time string to the date string and parsing them together, though by that point I've already parsed the date (which I also need separately) as a `Date` anyway.

**Comment by omus** [comment]
You are correct that `Base.Dates.Time` is not in 0.5. At the moment `Base.Dates.Time` doesn't support parsing which may be a show stopper for you.

I'm not against making `TimeOffset` exported but I feel if I do that I should probably make `TimeOffset` into its own package and do a little more work on the interface.

**Comment by joshbode** [comment]
Given `Base.Dates.Time` I probably could do something like this and avoid `TimeOffset` entirely, then:
```julia
tz = localzone()
d, t = "2016-07-03", "10:34:23"
d = Date(d)
t = Time(map(float, split(t, ':'; limit=3))...)
dt = ZonedDateTime(d + t, tz)
```
then I get to keep the date (and only parse it once), too.

**Comment by omus** [comment]
You may want to parse as an `Int`.
```julia
map(n -> parse(Int, n), split(t, ':'; limit=3))
```
Feel free to make a PR to add a `parse(::Type{Time}, s::AbstractString)` method in Base.

**Comment by joshbode** [comment]
I might just do that :)

**Comment by joshbode** [comment]
JuliaLang/julia/pull/22163
