### ISSUE TITLE
localzone() on Win10 fails

### ISSUE THREAD

**Issue by JeffreySarnoff** [JuliaTime/TimeZones.jl#90]
current master (localzone() used to work)

```
julia> localzone()
ERROR: unable to translate to POSIX time zone name from: "Eastern Standard Time"
```

Julia Version 0.6.0
Commit 903644385b* (2017-06-19 13:05 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-6820HK CPU @ 2.70GHz

**Comment by omus** [comment]
What is the output of running `Pkg.build("TimeZones")`?

**Comment by JeffreySarnoff** [comment]
julia> Pkg.build("TimeZones")
INFO: Building WinRPM
WARNING: Compat.KERNEL is deprecated.
  likely near C:\Users\jas\.julia\v0.6\WinRPM\src\WinRPM.jl:4
INFO: Downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_Leap_42.2/repodata/repomd.xml
INFO: Downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_Leap_42.2/repodata/repomd.xml
INFO: Building LightXML
WARNING: Compat.KERNEL is deprecated.
  likely near C:\Users\jas\.julia\v0.6\WinRPM\src\WinRPM.jl:4
INFO: Nothing to do
INFO: Building TimeZones
INFO: Extracting tzdata archive

7-Zip [64] 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18

Processing archive: C:\Users\jas\.julia\v0.6\TimeZones.jl\deps\tzarchive\tzdata2017b.tar.gz

Extracting  tzdata2017b.tar

Everything is Ok

Size:       983040
Compressed: 324317
INFO: Converting tz source files into TimeZone data
INFO: Compiling Windows time zone name translation
INFO: Successfully built TimeZones

after rebuilding
```
julia> using TimeZones

julia> localzone()
ERROR: unable to translate to POSIX time zone name from: "Eastern Standard Time"
Stacktrace:
 [1] localzone() at C:\Users\jas\.julia\v0.6\TimeZones.jl\src\local.jl:143
```

**Comment by omus** [comment]
Thanks. What is the output you have for `TimeZones.WindowsTimeZoneIDs.WINDOWS_TRANSLATION`?

**Comment by JeffreySarnoff** [comment]
funny you should ask -- I just did that. windowsZones.xml  looks right. but
```

julia> TimeZones.WINDOWS_TRANSLATION
Dict{AbstractString,AbstractString} with 0 entries
```

**Comment by JeffreySarnoff** [comment]
```julia
> WINDOWS_XML_FILE = "v0.6\\TimeZones\\deps\\local\\windowsZones.xml"
> translation = TimeZones.WindowsTimeZoneIDs.compile(WINDOWS_XML_FILE)
> translation["Eastern Standard Time"]
"America/New_York"
```
I can do that

**Comment by JeffreySarnoff** [comment]
My system setup for v0.6 somehow may be the problem -- It works for me on v0.7.
Please do not spend more time on this until I reinstall v0.6 and see how it goes --

**Comment by omus** [comment]
Ok, let me know how things go.

**Comment by JeffreySarnoff** [comment]
my problem, not yours
